/**
 * Clipboard Service - Copy analysis results in formatted text
 */

export interface AnalysisResultText {
  fileName: string
  prediction: 'real' | 'synthetic'
  confidence: number
  spatialScore: number
  frequencyScore: number
  aiGenerationScore: number
  deepfakeScore: number
  manipulationScore: number
  prnuSensorScore: number
  processingTime: number
}

/**
 * Format analysis result as readable text
 */
export function formatAnalysisAsText(result: AnalysisResultText): string {
  const predictionEmoji = result.prediction === 'synthetic' ? '⚠️' : '✅'
  const confidencePercent = (result.confidence * 100).toFixed(2)

  return `
${predictionEmoji} AI MEDIA FORENSICS ANALYSIS REPORT

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FILE INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
File Name: ${result.fileName}
Analysis Date: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PREDICTION RESULT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Prediction: ${result.prediction.toUpperCase()}
Confidence: ${confidencePercent}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORENSIC SCORES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔍 Spatial Score:            ${(result.spatialScore * 100).toFixed(2)}%
📊 Frequency Score:          ${(result.frequencyScore * 100).toFixed(2)}%
🤖 AI Generation Score:      ${(result.aiGenerationScore * 100).toFixed(2)}%
🎭 Deepfake Score:           ${(result.deepfakeScore * 100).toFixed(2)}%
✂️  Manipulation Score:        ${(result.manipulationScore * 100).toFixed(2)}%
📷 PRNU Sensor Score:        ${(result.prnuSensorScore * 100).toFixed(2)}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROCESSING INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Processing Time: ${result.processingTime}ms
Analysis Model: PyTorch + Airia AI Ensemble
Detection Method: Multi-Layer Forensic Analysis

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INTERPRETATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${
  result.prediction === 'synthetic'
    ? `🚨 HIGH PROBABILITY OF AI-GENERATED CONTENT
This media is likely generated using AI technology (DALL-E, Midjourney, Stable Diffusion, etc.) or heavily manipulated.
Confidence: ${confidencePercent}% - Recommend manual review for critical decisions.`
    : `✅ HIGH PROBABILITY OF AUTHENTIC CONTENT
This media appears to be genuine and not AI-generated. However, always verify through additional sources.
Confidence: ${confidencePercent}% - Recommended for use with caution in critical applications.`
}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISCLAIMER
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This analysis is based on machine learning algorithms and should not be
considered as definitive proof. Always use in conjunction with other
verification methods. For legal or critical purposes, seek expert review.

Generated by AI Media Forensics System
https://github.com/Sneh9110/AI-Media-Forensics-System
`.trim()
}

/**
 * Copy text to clipboard with fallback
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    // Try modern Clipboard API first
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    }

    // Fallback for older browsers
    const textArea = document.createElement('textarea')
    textArea.value = text
    textArea.style.position = 'fixed'
    textArea.style.left = '-999999px'
    document.body.appendChild(textArea)
    textArea.select()
    const success = document.execCommand('copy')
    document.body.removeChild(textArea)
    return success
  } catch (error) {
    console.error('Failed to copy to clipboard:', error)
    return false
  }
}

/**
 * Copy analysis result as formatted text
 */
export async function copyAnalysisToClipboard(result: AnalysisResultText): Promise<boolean> {
  const text = formatAnalysisAsText(result)
  return copyToClipboard(text)
}
/**
 * Data encryption utility for sensitive analysis results
 */
export class DataEncryption {
  private static readonly ALGORITHM = "aes-256-cbc"

  /**
   * Encrypt sensitive data using simple XOR cipher
   * For production use bcrypt or crypto-js
   */
  static encryptData(data: string, key: string): string {
    let encrypted = ""
    for (let i = 0; i < data.length; i++) {
      const dataChar = data.charCodeAt(i)
      const keyChar = key.charCodeAt(i % key.length)
      encrypted += String.fromCharCode(dataChar ^ keyChar)
    }
    return Buffer.from(encrypted).toString("base64")
  }

  /**
   * Decrypt data using simple XOR cipher
   */
  static decryptData(encrypted: string, key: string): string {
    const data = Buffer.from(encrypted, "base64").toString()
    let decrypted = ""
    for (let i = 0; i < data.length; i++) {
      const dataChar = data.charCodeAt(i)
      const keyChar = key.charCodeAt(i % key.length)
      decrypted += String.fromCharCode(dataChar ^ keyChar)
    }
    return decrypted
  }

  /**
   * Create data hash for integrity verification
   */
  static createHash(data: string): string {
    let hash = 0
    for (let i = 0; i < data.length; i++) {
      const char = data.charCodeAt(i)
      hash = (hash << 5) - hash + char
      hash = hash & hash // Convert to 32bit integer
    }
    return hash.toString(16)
  }
}